# Autogenerated by tools/build/setup_cmake.py
# from tools/build/cmake_templates/Module.cmake
# Do not edit - any changes will be lost!

project(IMP.insulinsecretion)



if(DEFINED IMP_insulinsecretion_IS_CUDA OR DEFINED IMP_IS_CUDA)
  set(CUDA_DEFINES ":IMP_INSULINSECRETION_CUDA_LIB")
else()
  set(CUDA_DEFINES "")
endif()

imp_get_process_exit_code("Setting up module insulinsecretion" status ${CMAKE_BINARY_DIR}
                          COMMAND ${PYTHON_EXECUTABLE}
                          /usr/local/share/IMP/tools/build/setup_module.py
                          --build_dir=/usr/local/share/IMP/build_info  --name=insulinsecretion
                          --datapath=${IMP_DATAPATH}
                          --defines=${IMP_insulinsecretion_CONFIG}:${CUDA_DEFINES}
                          --source=${CMAKE_SOURCE_DIR}
                          )

if(${status} EQUAL 0)
  imp_execute_process("setup_swig_wrappers insulinsecretion" ${CMAKE_BINARY_DIR}
    COMMAND ${PYTHON_EXECUTABLE} /usr/local/share/IMP/tools/build/setup_swig_wrappers.py
    --build_dir=/usr/local/share/IMP/build_info  --module=insulinsecretion
    --datapath=${IMP_DATAPATH}
    --source=${CMAKE_SOURCE_DIR})

  # for warning control
  add_definitions(-DIMPINSULINSECRETION_COMPILATION)

  if(0 EQUAL 0)
    set(allh_command  "${PYTHON_EXECUTABLE}" "/usr/local/share/IMP/tools/dev_tools/make_all_header.py" "${CMAKE_BINARY_DIR}/include/IMP/insulinsecretion.h" "IMP/insulinsecretion" "${PROJECT_SOURCE_DIR}/include/" ${IMP_insulinsecretion_EXTRA_HEADERS})
    # for swig
    imp_execute_process("IMP.insulinsecretion making all header" ${PROJECT_BINARY_DIR}
                        COMMAND ${allh_command})

    add_custom_target(IMP.insulinsecretion-all-header
      COMMAND ${allh_command}
      DEPENDS "/usr/local/share/IMP/tools/dev_tools/make_all_header.py")
    set_property(TARGET "IMP.insulinsecretion-all-header" PROPERTY FOLDER "IMP.insulinsecretion")
    list(APPEND IMP_insulinsecretion_LIBRARY_EXTRA_DEPENDENCIES IMP.insulinsecretion-all-header)
  endif()

  
  if(IMP_DOXYGEN_FOUND)
    # documentation
    file(GLOB headers ${CMAKE_BINARY_DIR}/include/IMP/insulinsecretion/*.h)
    file(GLOB docs ${CMAKE_SOURCE_DIR}/doc/*.dox
      ${CMAKE_SOURCE_DIR}/doc/*.md)
    file(GLOB examples ${CMAKE_BINARY_DIR}/doc/examples/insulinsecretion/*.py
      ${CMAKE_BINARY_DIR}/doc/examples/insulinsecretion/*.cpp)

    if(NOT IMP_STATIC)
      set(IMP_insulinsecretion_TAG_DEPENDS "${IMP.insulinsecretion-python}")
    endif()

    add_custom_command(OUTPUT ${CMAKE_BINARY_DIR}/doxygen/insulinsecretion/tags ${CMAKE_BINARY_DIR}/doxygen/insulinsecretion/xml/index.xml
      COMMAND mkdir -p ${CMAKE_BINARY_DIR}/doc/html
      COMMAND ln -s -f ../../include
      COMMAND ln -s -f ../../doc/examples
      COMMAND ln -s -f ../../lib
      COMMAND ${IMP_DOXYGEN_EXECUTABLE} ../../doxygen/insulinsecretion/Doxyfile 2>&1 /dev/null
      COMMAND ${PYTHON_EXECUTABLE} /usr/local/share/IMP/tools/build/doxygen_patch_tags.py --module=insulinsecretion --file=../../doxygen/insulinsecretion/tags
      COMMAND ${PYTHON_EXECUTABLE} /usr/local/share/IMP/tools/build/doxygen_show_warnings.py --warn=../../doxygen/insulinsecretion/warnings.txt
      COMMAND ${PYTHON_EXECUTABLE} /usr/local/share/IMP/tools/build/doxygen_spell_check.py xml ${CMAKE_SOURCE_DIR}/test/standards_exceptions
      DEPENDS ${IMP_kernel_DOC}
${IMP_cgal_DOC}
${IMP_algebra_DOC}
${IMP_display_DOC}
${IMP_score_functor_DOC}
${IMP_core_DOC}
${IMP_container_DOC} ${headers} ${docs} ${examples} ${CMAKE_SOURCE_DIR}/README.md ${IMP_insulinsecretion_TAG_DEPENDS}
      WORKING_DIRECTORY ${CMAKE_BINARY_DIR}/doxygen/insulinsecretion/
      COMMENT "Running doxygen on insulinsecretion")

    add_custom_target("IMP.insulinsecretion-doc" ALL DEPENDS ${CMAKE_BINARY_DIR}/doxygen/insulinsecretion/tags)
    set_property(TARGET "IMP.insulinsecretion-doc" PROPERTY FOLDER "IMP.insulinsecretion")
    set(IMP_insulinsecretion_DOC "IMP.insulinsecretion-doc" CACHE INTERNAL "" FORCE)

    if(NOT IMP_STATIC)
      list(APPEND IMP_DOC_DEPENDS "${IMP.insulinsecretion-python}")
    endif()
    list(REMOVE_DUPLICATES IMP_DOC_DEPENDS)
    set(IMP_DOC_DEPENDS ${IMP_DOC_DEPENDS} CACHE INTERNAL "" FORCE)
  else()
    set(IMP_insulinsecretion_DOC "" CACHE INTERNAL "" FORCE)
  endif(IMP_DOXYGEN_FOUND)

  if(0 EQUAL 0)
    list(APPEND imp_insulinsecretion_libs ${IMP_kernel_LIBRARY};${IMP_cgal_LIBRARY};${IMP_algebra_LIBRARY};${IMP_display_LIBRARY};${IMP_score_functor_LIBRARY};${IMP_core_LIBRARY};${IMP_container_LIBRARY})
    list(APPEND imp_insulinsecretion_libs ${BOOST.SYSTEM_LIBRARIES};${GPERFTOOLS_LIBRARIES};${BOOST.FILESYSTEM_LIBRARIES};${NUMPY_LIBRARIES};${BOOST.RANDOM_LIBRARIES};${BOOST.PROGRAMOPTIONS_LIBRARIES};${CGAL_LIBRARIES};${ANN_LIBRARIES};${HDF5_LIBRARIES};${PYTHON-IHM_LIBRARIES})
    list(REMOVE_DUPLICATES imp_insulinsecretion_libs)

    add_custom_command(
	OUTPUT ${CMAKE_BINARY_DIR}/lib/IMP/insulinsecretion/_version_check.py
               ${CMAKE_BINARY_DIR}/src/insulinsecretion_config.cpp
        COMMAND ${PYTHON_EXECUTABLE} /usr/local/share/IMP/tools/build/make_module_version.py
	        --name=insulinsecretion --datapath=${IMP_DATAPATH}
		--source=${CMAKE_SOURCE_DIR}
        DEPENDS IMP-version
        WORKING_DIRECTORY ${CMAKE_BINARY_DIR}/
        COMMENT "Building module version info")

    add_custom_target("IMP.insulinsecretion-version" ALL DEPENDS
                      ${CMAKE_BINARY_DIR}/lib/IMP/insulinsecretion/_version_check.py
                      ${CMAKE_BINARY_DIR}/src/insulinsecretion_config.cpp)
    set_property(TARGET "IMP.insulinsecretion-version" PROPERTY FOLDER "IMP.insulinsecretion")
    install(FILES "${CMAKE_BINARY_DIR}/lib/IMP/insulinsecretion/_version_check.py"
	    DESTINATION "${CMAKE_INSTALL_PYTHONDIR}/IMP/insulinsecretion/")
   endif()

  add_subdirectory(${CMAKE_SOURCE_DIR}/src)
add_subdirectory(${CMAKE_SOURCE_DIR}/test)
add_subdirectory(${CMAKE_SOURCE_DIR}/examples)
add_subdirectory(${CMAKE_SOURCE_DIR}/benchmark)
add_subdirectory(${CMAKE_SOURCE_DIR}/bin)
add_subdirectory(${CMAKE_SOURCE_DIR}/utility)
  set(IMP_insulinsecretion "IMP.insulinsecretion" CACHE INTERNAL "" FORCE)
else()

  # make sure it is empty
  set(IMP_insulinsecretion_DOC "" CACHE INTERNAL "" FORCE)
  set(IMP_insulinsecretion_PYTHON "" CACHE INTERNAL "" FORCE)
  set(IMP_insulinsecretion "" CACHE INTERNAL "" FORCE)

  if(${status} EQUAL 1)
    message(FATAL_ERROR "Module IMP.insulinsecretion disabled")
  else()
    message(FATAL_ERROR "setup_module returned ${status}")
  endif()
  set(IMP_insulinsecretion_LIBRARY CACHE INTERNAL "" FORCE)
endif()
